spring:
  application:
    name: auth-service
  config:
    import: vault://
  security:
    oauth2:
      resourceserver:
        jwt:
          # URL del tuo realm per validare i token in ingresso
          issuer-uri: ${KEYCLOAK_ISSUER_URI} # Verrà da Vault o variabile d'ambiente
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI} # Verrà da Vault o variabile d'ambiente
  datasource:
    # La URL del database, configurabile via variabile d'ambiente o con un default coerente con docker-compose
    url: ${AUTH_DB_URL} # Verrà da Vault o variabile d'ambiente
    # username e password verranno letti da Vault
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  cloud:
    vault:
      host: localhost # CAMBIATO DA 'vault' A 'localhost' per esecuzione locale
      port: 8200
      scheme: http
      authentication: TOKEN
      token: my-root-token # ATTENZIONE: Non hardcodare in produzione! Usare variabili d'ambiente o altri metodi sicuri.
      kv:
        enabled: true
        backend: secret
        default-context: auth-service

# Parametri personalizzati per l'Admin Client
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL} # Ora il valore di default verrà da Vault o da una variabile d'ambiente
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: ${AUTH_PORT:8085}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.ginogipsy.sanmartino: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized